const AppActionTypes = {

  CREATE_MODAL: 'CREATE_MODAL',
  DISMISS_MODAL: 'DISMISS_MODAL',

  CREATE_FLASH_MESSAGE: 'CREATE_FLASH_MESSAGE',
  DISMISS_FLASH_MESSAGE: 'DISMISS_FLASH_MESSAGE'

};

export default AppActionTypes;