const AuthActionTypes = {

  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

  CREATE_COMPANY_WITH_USER_SUCCESS: 'CREATE_COMPANY_WITH_USER_SUCCESS',
  CREATE_COMPANY_WITH_USER_SUCCESS_SUCCESS: 'CREATE_COMPANY_WITH_USER_SUCCESS_SUCCESS'
  
}

export default AuthActionTypes;