const AuthActionTypes = {

  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  CREATE_COMPANY_WITH_USER_SUCCESS: 'CREATE_COMPANY_WITH_USER_SUCCESS',
  CREATE_COMPANY_WITH_USER_SUCCESS_SUCCESS: 'CREATE_COMPANY_WITH_USER_SUCCESS_SUCCESS'
  
}

export default AuthActionTypes;