import {createConstants} from 'create-reducer-redux';

const CollectionActionTypes = createConstants([
  'CREATE_COLLECTION_SUCCESS',
  'DELETE_COLLECTION_SUCCESS',
  'FETCH_COLLECTIONS_ERROR',
  'FETCH_COLLECTIONS_SUCCESS',
  'FETCH_COLLECTION_BEING_VIEWED_SUCCESS',
  'RESET_COLLECTION_BEING_EDITED',
  'RESET_COLLECTION_BEING_VIEWED',
  'RESET_SHOULD_FETCH_COLLECTIONS',
  'SET_COLLECTION_BEING_EDITED',
  'SET_COLLECTION_BEING_VIEWED',
  'UPDATE_COLLECTION_SUCCESS'
]);

export default CollectionActionTypes;
