const CollectionActionTypes = {
  CREATE_COLLECTION_SUCCESS: 'CREATE_COLLECTION_SUCCESS',
  DELETE_COLLECTION_SUCCESS: 'DELETE_COLLECTION_SUCCESS',

  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_SUCCESS',

  RESET_SHOULD_FETCH_COLLECTIONS: 'RESET_SHOULD_FETCH_COLLECTIONS'
}

export default CollectionActionTypes;