const DocumentNewActionTypes = {

  ADD_SIGNERS: 'ADD_SIGNERS',
  CREATE_DOCUMENTS_SUCCESS: 'CREATE_DOCUMENTS_SUCCESS',
  GENERATE_GENERAL_PLACEHOLDER_FORM_FIELDS: 'GENERATE_GENERAL_PLACEHOLDER_FORM_FIELDS',
  GENERATE_SPECIFIC_PLACEHOLDER_FORM_FIELDS: 'GENERATE_SPECIFIC_PLACEHOLDER_FORM_FIELDS',
  REMOVE_SIGNER: 'REMOVE_SIGNER',
  RESET_STATE: 'RESET_STATE',
  SET_COLLECTION: 'SET_COLLECTION',
  SET_EMAILS_SENT_COUNT: 'SET_EMAILS_SENT_COUNT',
  SET_TEMPLATE: 'SET_TEMPLATE',
  UPDATE_GENERAL_PLACEHOLDER_FORM_FIELD: 'UPDATE_GENERAL_PLACEHOLDER_FORM_FIELD',
  UPDATE_SPECIFIC_PLACEHOLDER_FORM_FIELD: 'UPDATE_SPECIFIC_PLACEHOLDER_FORM_FIELD'

};

export default DocumentNewActionTypes;
