const DocumentActionTypes = {
  FETCH_DOCUMENTS_SUCCESS: 'FETCH_DOCUMENTS_SUCCESS',
  FETCH_DOCUMENTS_ERROR: 'FETCH_DOCUMENTS_ERROR',

  RESET_SHOULD_FETCH_DOCUMENTS: 'RESET_SHOULD_FETCH_DOCUMENTS'
};

export default DocumentActionTypes;
