import createConstants from './utils/createConstants';

const DocumentNewActionTypes = createConstants([
  'ADD_SIGNER',
  'ADD_SIGNERS',
  'CLEAR_SPECIFIC_PLACEHOLDER_FORM',
  'CREATE_DOCUMENTS_SUCCESS',
  'GENERATE_GENERAL_PLACEHOLDER_FORM_FIELDS',
  'GENERATE_SPECIFIC_PLACEHOLDER_FORM_FIELDS',
  'REMOVE_SIGNER',
  'RESET_STATE',
  'SET_COLLECTION',
  'SET_EMAILS_SENT_COUNT',
  'SET_TEMPLATE',
  'UPDATE_GENERAL_PLACEHOLDER_FORM_FIELD',
  'UPDATE_SPECIFIC_PLACEHOLDER_FORM_FIELD'
]);

export default DocumentNewActionTypes;
