const TemplateActionTypes = {
  CREATE_TEMPLATE_SUCCESS: 'CREATE_TEMPLATE_SUCCESS',

  FETCH_TEMPLATES_SUCCESS: 'FETCH_TEMPLATES_SUCCESS',
  RESET_TEMPLATE_CREATED: 'RESET_TEMPLATE_CREATED'
}

export default TemplateActionTypes;